package testsuites

import (
	"encoding/json"
	"io"
	"os"
	"reflect"

	"github.com/kubeshop/testkube/cmd/kubectl-testkube/commands/common"
	testkubeapiv1 "github.com/kubeshop/testkube/pkg/api/v1/client"
	"github.com/kubeshop/testkube/pkg/api/v1/testkube"
	"github.com/kubeshop/testkube/pkg/ui"
	"github.com/spf13/cobra"
)

func UpdateTestSuitesCmd() *cobra.Command {

	var (
		file                     string
		name                     string
		labels                   map[string]string
		schedule                 string
		executionName            string
		variables                map[string]string
		secretVariables          map[string]string
		httpProxy, httpsProxy    string
		secretVariableReferences map[string]string
		timeout                  int32
	)

	cmd := &cobra.Command{
		Use:   "testsuite",
		Short: "Update Test Suite",
		Long:  `Update Test Custom Resource Definitions, `,
		Run: func(cmd *cobra.Command, args []string) {

			var content []byte
			var err error

			if file != "" {
				// read test content
				content, err = os.ReadFile(file)
				ui.ExitOnError("reading file"+file, err)
			} else if stat, _ := os.Stdin.Stat(); (stat.Mode() & os.ModeCharDevice) == 0 {
				content, err = io.ReadAll(os.Stdin)
				ui.ExitOnError("reading stdin", err)
			}

			var options testkubeapiv1.UpsertTestSuiteOptions

			err = json.Unmarshal(content, &options)
			ui.ExitOnError("Invalid file content", err)

			if name != "" {
				options.Name = name
			}

			if options.Name == "" {
				ui.Failf("pass valid test suite name (in '--name' flag)")
			}

			client, namespace := common.GetClient(cmd)
			options.Namespace = namespace

			testSuite, _ := client.GetTestSuite(options.Name)
			if options.Name != testSuite.Name {
				ui.Failf("TestSuite with name '%s' not exists in namespace %s", options.Name, options.Namespace)
			}

			// if labels are passed and are different from the existing overwrite
			if len(labels) > 0 && !reflect.DeepEqual(testSuite.Labels, labels) {
				options.Labels = labels
			} else {
				options.Labels = testSuite.Labels
			}

			variables, err := common.CreateVariables(cmd)
			ui.ExitOnError("Invalid variables", err)

			options.ExecutionRequest = &testkube.TestSuiteExecutionRequest{
				Variables:  variables,
				Name:       cmd.Flag("execution-name").Value.String(),
				HttpProxy:  cmd.Flag("http-proxy").Value.String(),
				HttpsProxy: cmd.Flag("https-proxy").Value.String(),
				Timeout:    timeout,
			}

			options.Schedule = cmd.Flag("schedule").Value.String()

			err = validateSchedule(options.Schedule)
			ui.ExitOnError("validating schedule", err)

			testSuite, err = client.UpdateTestSuite(options)
			ui.ExitOnError("updating TestSuite "+options.Name+" in namespace "+options.Namespace, err)
			ui.Success("TestSuite updated", options.Name)
		},
	}

	cmd.Flags().StringVarP(&file, "file", "f", "", "JSON test file - will be read from stdin if not specified, look at testkube.TestUpsertRequest")
	cmd.Flags().StringVar(&name, "name", "", "Set/Override test suite name")
	cmd.Flags().StringToStringVarP(&labels, "label", "l", nil, "label key value pair: --label key1=value1")
	cmd.Flags().StringToStringVarP(&variables, "variable", "v", nil, "param key value pair: --variable key1=value1")
	cmd.Flags().StringToStringVarP(&secretVariables, "secret-variable", "s", nil, "secret variable key value pair: --secret-variable key1=value1")
	cmd.Flags().StringVarP(&schedule, "schedule", "", "", "test suite schedule in a cronjob form: * * * * *")
	cmd.Flags().StringVarP(&executionName, "execution-name", "", "", "execution name, if empty will be autogenerated")
	cmd.Flags().StringVar(&httpProxy, "http-proxy", "", "http proxy for executor containers")
	cmd.Flags().StringToStringVarP(&secretVariableReferences, "secret-variable-reference", "", nil, "secret variable references in a form name1=secret_name1=secret_key1")
	cmd.Flags().StringVar(&httpsProxy, "https-proxy", "", "https proxy for executor containers")
	cmd.Flags().Int32Var(&timeout, "timeout", 0, "duration in seconds for test suite to timeout. 0 disables timeout.")

	return cmd
}
