{{- if .Values.podDisruptionBudget.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ include "testkube-runner.fullname" . }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable (not .Values.podDisruptionBudget.minAvailable) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1  }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-runner.selectorLabels" . | nindent 6 }}
{{- else if .Values.global.podDisruptionBudget.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: "{{ include "testkube-runner.fullname" . }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.global.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.global.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.global.podDisruptionBudget.maxUnavailable (not .Values.global.podDisruptionBudget.minAvailable) }}
  maxUnavailable: {{ .Values.global.podDisruptionBudget.maxUnavailable | default 1  }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-runner.selectorLabels" . | nindent 6 }}
{{- end }}
