# Create Service Account for the Agent
{{- if .Values.pod.serviceAccount.autoCreate }}
{{- $runnerServiceAccountAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.global.annotations)) (deepCopy (default (dict) .Values.pod.serviceAccount.annotations)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.pod.serviceAccount.name }}
  name: "{{ .Values.pod.serviceAccount.name }}"
  {{- else }}
  name: "agent-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $runnerServiceAccountAnnotations }}
    {{- toYaml $runnerServiceAccountAnnotations | nindent 4 }}
    {{- end }}
{{- end }}

---

# Create Service Account for Execution workers in a default namespace
{{- if .Values.execution.default.serviceAccount.autoCreate }}
{{- $defaultExecutionNamespace := default .Release.Namespace .Values.execution.default.namespace }}
{{- $defaultExecutionServiceAccountAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.global.annotations)) (deepCopy (default (dict) .Values.execution.default.serviceAccount.annotations)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.execution.default.serviceAccount.name }}
  name: "{{ .Values.execution.default.serviceAccount.name }}"
  {{- else }}
  name: "exec-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ $defaultExecutionNamespace }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $defaultExecutionServiceAccountAnnotations }}
    {{- toYaml $defaultExecutionServiceAccountAnnotations | nindent 4 }}
    {{- end }}
{{- end }}

# Create Service Account for Execution workers in other namespaces
{{- range $ns, $data := .Values.execution.additionalNamespaces }}
{{ with $ }}
{{- if and $data.serviceAccount $data.serviceAccount.autoCreate }}
{{- $additionalExecutionServiceAccountAnnotations := mergeOverwrite (deepCopy (default (dict) .Values.global.annotations)) (deepCopy (default (dict) $data.serviceAccount.annotations)) }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if $data.serviceAccount.name }}
  name: "{{ $data.serviceAccount.name }}"
  {{- else }}
  name: "exec-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ $ns }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $additionalExecutionServiceAccountAnnotations }}
    {{- toYaml $additionalExecutionServiceAccountAnnotations | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
