# Create Service Account for the Agent
{{- if .Values.pod.serviceAccount.autoCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.pod.serviceAccount.name }}
  name: "{{ .Values.pod.serviceAccount.name }}"
  {{- else }}
  name: "agent-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
{{- end }}

---

# Create Service Account for Execution workers in a default namespace
{{- if .Values.execution.default.serviceAccount.autoCreate }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.execution.default.serviceAccount.name }}
  name: "{{ .Values.execution.default.serviceAccount.name }}"
  {{- else }}
  name: "exec-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
{{- end }}

# Create Service Account for Execution workers in other namespaces
{{- range $ns, $data := .Values.execution.additionalNamespaces }}
{{ with $ }}
{{- if and $data.serviceAccount $data.serviceAccount.autoCreate }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if $data.serviceAccount.name }}
  name: "{{ $data.serviceAccount.name }}"
  {{- else }}
  name: "exec-sa-{{ .Release.Name }}"
  {{- end }}
  namespace: "{{ $ns }}"
  labels:
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
