{{- if and .Values.seaweedfs.enabled .Values.seaweedfs.filer.s3.enableAuth }}
{{- $testkubeApi := index .Values "testkube-api" }}
{{- $storage := index $testkubeApi "storage" }}
{{- $accessKey := index $storage "accessKeyId" | default "testkube" }}
{{- $secretKey := index $storage "accessKey" | default "t3stkub3-3nt3rpr1s3" }}
{{- $configSecretName := .Values.seaweedfs.filer.s3.existingConfigSecret | default "testkube-seaweedfs-s3-config" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $configSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "global.labels.standard" . | nindent 4 }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {
          "name": "testkube-storage",
          "credentials": [
            {
              "accessKey": "{{ $accessKey }}",
              "secretKey": "{{ $secretKey }}"
            }
          ],
          "actions": ["Admin", "Read", "Write", "List", "Tagging"]
        }
      ]
    }
{{- end }}
