// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube/pkg/executiondata (interfaces: ExecutionRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock_repository.go -package=executiondata github.com/kubeshop/testkube/pkg/executiondata ExecutionRepository
//

// Package executiondata is a generated GoMock package.
package executiondata

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutionRepository is a mock of ExecutionRepository interface.
type MockExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutionRepositoryMockRecorder is the mock recorder for MockExecutionRepository.
type MockExecutionRepositoryMockRecorder struct {
	mock *MockExecutionRepository
}

// NewMockExecutionRepository creates a new mock instance.
func NewMockExecutionRepository(ctrl *gomock.Controller) *MockExecutionRepository {
	mock := &MockExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionRepository) EXPECT() *MockExecutionRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockExecutionRepository) Get(ctx context.Context, id string) (Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExecutionRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExecutionRepository)(nil).Get), ctx, id)
}

// ListArtifacts mocks base method.
func (m *MockExecutionRepository) ListArtifacts(ctx context.Context, id string, patterns []string) ([]Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArtifacts", ctx, id, patterns)
	ret0, _ := ret[0].([]Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArtifacts indicates an expected call of ListArtifacts.
func (mr *MockExecutionRepositoryMockRecorder) ListArtifacts(ctx, id, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArtifacts", reflect.TypeOf((*MockExecutionRepository)(nil).ListArtifacts), ctx, id, patterns)
}
