version: "2"

linters:
  default: none
  enable:
    - govet
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kubeshop/testkube
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
