version: "2"

linters:
  default: none
  enable:
    - govet
    - revive
    - staticcheck
    - unused
    - ineffassign
    - noctx
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kubeshop/testkube
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
