---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: testkube
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: testkube-oss-runner
  title: Testkube OSS/Runner
  description: Testkube OSS/Runner is a cloud native test orchestration and execution platform for Kubernetes.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/articles/install/standalone-agent
    testkube.io/organization: testkube
    testkube.io/environments: testkube-cloud-test-dev
    testkube.io/labels: tool=testkube-oss
  tags:
  - go
  - kubernetes
  - testing
  - ci-cd
spec:
  owner: group:testkube
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testkube-api-server
  title: Testkube Agent
  description: Testkube Agent is a component of Testkube that runs as a Kubernetes controller and is responsible for orchestrating test execution and managing test resources in the cluster.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/articles/install/standalone-agent
  tags:
  - go
  - kubernetes
  - testing
  - ci-cd
spec:
  type: service
  owner: group:testkube
  system: testkube-oss-runner
  lifecycle: production
  dependsOn:
  - component:testkube-testworkflow-init
  - component:testkube-testworkflow-toolkit
  providesApis:
  - api:testkube-api-server
  links:
  - url: https://github.com/kubeshop/testkube/blob/backstage/.github/workflows/new-build.yaml
    title: New Build CI/CD Workflow
    icon: github
  - url: https://github.com/kubeshop/testkube/actions?query=workflow:new-build
    title: Build Actions
    icon: dashboard
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testkube-api-server
  title: Testkube Agent API
  description: The API provided by the Testkube Agent, which allows users to interact with the Testkube platform, manage test resources, and execute tests programmatically.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/openapi/overview#agent-api
spec:
  type: openapi
  owner: group:testkube
  system: testkube-oss-runner
  lifecycle: production
  definition:
    $text: ./api/v1/testkube.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testkube-kubectl
  title: Testkube CLI
  description: Testkube CLI is a command-line interface for Testkube that allows users to interact with the Testkube platform, manage test resources, and execute tests from their local development environment.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/articles/cli-config-reference
  tags:
  - go
  - kubernetes
  - cli
spec:
  type: library
  owner: group:testkube
  system: testkube-oss-runner
  lifecycle: production
  links:
  - url: https://github.com/kubeshop/testkube/blob/backstage/.github/workflows/new-build.yaml
    title: New Build CI/CD Workflow
    icon: github
  - url: https://github.com/kubeshop/testkube/actions?query=workflow:new-build
    title: Build Actions
    icon: dashboard
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testkube-testworkflow-init
  title: Testkube TestWorkflow Init Container
  description: Testkube TestWorkflow Init Container is a component of Testkube that runs as an init container in test execution pods and is responsible for preparing the test environment, such as setting up necessary files, configurations, and dependencies before the main test execution container starts.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/articles/install/standalone-agent
  tags:
  - go
  - kubernetes
  - testing
  - ci-cd
spec:
  type: service
  owner: group:testkube
  system: testkube-oss-runner
  lifecycle: production
  links:
  - url: https://github.com/kubeshop/testkube/blob/backstage/.github/workflows/new-build.yaml
    title: New Build CI/CD Workflow
    icon: github
  - url: https://github.com/kubeshop/testkube/actions?query=workflow:new-build
    title: Build Actions
    icon: dashboard
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testkube-testworkflow-toolkit
  title: Testkube TestWorkflow Toolkit
  description: Testkube TestWorkflow Toolkit is a component of Testkube that provides reusable tools and utilities for test workflows, such as setting up necessary files, configurations, and dependencies before the main test execution container starts.
  annotations:
    github.com/project-slug: kubeshop/testkube
    backstage.io/techdocs-ref: url:https://docs.testkube.io/articles/install/standalone-agent
  tags:
  - go
  - kubernetes
  - testing
  - ci-cd
spec:
  type: service
  owner: group:testkube
  system: testkube-oss-runner
  lifecycle: production
  links:
  - url: https://github.com/kubeshop/testkube/blob/backstage/.github/workflows/new-build.yaml
    title: New Build CI/CD Workflow
    icon: github
  - url: https://github.com/kubeshop/testkube/actions?query=workflow:new-build
    title: Build Actions
    icon: dashboard
