apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
        - name: "{{ .Name }}"
          image: {{ .Image }}
          imagePullPolicy: Always
          command:
            - "/bin/runner"
            - '{{ .Jsn }}'
          resources:
            limits:
              memory: 128Mi
