kubectl delete test -ntestkube postman-test-023mfa
kubectl delete test -ntestkube postman-test-13rgrn
kubectl delete test -ntestkube postman-test-1gj91g
kubectl delete test -ntestkube postman-test-1iekbd
kubectl delete test -ntestkube postman-test-2e4h08
kubectl delete test -ntestkube postman-test-32u3hj
kubectl delete test -ntestkube postman-test-56oazkh
kubectl delete test -ntestkube postman-test-5lq0ql
kubectl delete test -ntestkube postman-test-5uug7s
kubectl delete test -ntestkube postman-test-741o7u
kubectl delete test -ntestkube postman-test-7cmomd
kubectl delete test -ntestkube postman-test-an0x4c
kubectl delete test -ntestkube postman-test-c2mgpl
kubectl delete test -ntestkube postman-test-c8068j
kubectl delete test -ntestkube postman-test-cjc3mn
kubectl delete test -ntestkube postman-test-dg7g12
kubectl delete test -ntestkube postman-test-fbx1pj
kubectl delete test -ntestkube postman-test-fkwdgy
kubectl delete test -ntestkube postman-test-fp2657
kubectl delete test -ntestkube postman-test-gcsdna
kubectl delete test -ntestkube postman-test-huw9e4
kubectl delete test -ntestkube postman-test-im899f
kubectl delete test -ntestkube postman-test-ipl78p
kubectl delete test -ntestkube postman-test-irbyl0
kubectl delete test -ntestkube postman-test-j01we9
kubectl delete test -ntestkube postman-test-jgzrsr
kubectl delete test -ntestkube postman-test-k4hms2
kubectl delete test -ntestkube postman-test-kk8t6g
kubectl delete test -ntestkube postman-test-kn7r6u
kubectl delete test -ntestkube postman-test-l43pea
kubectl delete test -ntestkube postman-test-l6oelr
kubectl delete test -ntestkube postman-test-lmr24q
kubectl delete test -ntestkube postman-test-mhpn6f
kubectl delete test -ntestkube postman-test-mjj7ik
kubectl delete test -ntestkube postman-test-mxwgeg
kubectl delete test -ntestkube postman-test-n65bfbh
kubectl delete test -ntestkube postman-test-n8z1gh
kubectl delete test -ntestkube postman-test-nhhcva
kubectl delete test -ntestkube postman-test-pmgrss
kubectl delete test -ntestkube postman-test-pzposp
kubectl delete test -ntestkube postman-test-qfpucjh
kubectl delete test -ntestkube postman-test-qjm995h
kubectl delete test -ntestkube postman-test-qnfmru
kubectl delete test -ntestkube postman-test-sd1u84
kubectl delete test -ntestkube postman-test-sd2zaj
kubectl delete test -ntestkube postman-test-uff2ptm
kubectl delete test -ntestkube postman-test-ukmb4d
kubectl delete test -ntestkube postman-test-uv95ix
kubectl delete test -ntestkube postman-test-vxpk4b
kubectl delete test -ntestkube postman-test-w8d48k
kubectl delete test -ntestkube postman-test-xij0cg
kubectl delete test -ntestkube postman-test-y4vwtt
kubectl delete test -ntestkube postman-test-ybsn2o
kubectl delete test -ntestkube postman-test-zc6bbf
kubectl delete test -ntestkube postman-test-zsl8z9
