// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testkube/sync/v1/test_workflow_template.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestWorkflowTemplate contains a protobuf encoded representation of a
// TestWorkflowTemplate object.
type TestWorkflowTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload contains the following Go struct as JSON encoded data:
	//
	//	github.com/kubeshop/testkube/api/testworkflows/v1.TestWorkflowTemplate
	//
	// WARNING: A mismatch in versions between Agent and Control Plane
	// may result in a failed or partial marshaling of this data in
	// potentially incompatible ways. Please ensure that client and
	// server representations are passing the same data across this
	// message.
	// The rationale for this lazy implementation is that creating
	// a protobuf implementation of CRD data structures is both
	// time consuming, and similarly capable of causing incompatibilities
	// between the protobuf and CRD implementations. As a result this
	// loose data format will be used until CRD definition is moved
	// to a single source from which all required usages can be
	// automatically generated to ensure compatibility.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWorkflowTemplate) Reset() {
	*x = TestWorkflowTemplate{}
	mi := &file_testkube_sync_v1_test_workflow_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWorkflowTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWorkflowTemplate) ProtoMessage() {}

func (x *TestWorkflowTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_sync_v1_test_workflow_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWorkflowTemplate.ProtoReflect.Descriptor instead.
func (*TestWorkflowTemplate) Descriptor() ([]byte, []int) {
	return file_testkube_sync_v1_test_workflow_template_proto_rawDescGZIP(), []int{0}
}

func (x *TestWorkflowTemplate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_testkube_sync_v1_test_workflow_template_proto protoreflect.FileDescriptor

const file_testkube_sync_v1_test_workflow_template_proto_rawDesc = "" +
	"\n" +
	"-testkube/sync/v1/test_workflow_template.proto\x12\x10testkube.sync.v1\"0\n" +
	"\x14TestWorkflowTemplate\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayloadB\xd3\x01\n" +
	"\x14com.testkube.sync.v1B\x19TestWorkflowTemplateProtoP\x01Z>github.com/kubeshop/testkube/pkg/proto/testkube/sync/v1;syncv1\xa2\x02\x03TSX\xaa\x02\x10Testkube.Sync.V1\xca\x02\x10Testkube\\Sync\\V1\xe2\x02\x1cTestkube\\Sync\\V1\\GPBMetadata\xea\x02\x12Testkube::Sync::V1b\beditionsp\xe8\a"

var (
	file_testkube_sync_v1_test_workflow_template_proto_rawDescOnce sync.Once
	file_testkube_sync_v1_test_workflow_template_proto_rawDescData []byte
)

func file_testkube_sync_v1_test_workflow_template_proto_rawDescGZIP() []byte {
	file_testkube_sync_v1_test_workflow_template_proto_rawDescOnce.Do(func() {
		file_testkube_sync_v1_test_workflow_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testkube_sync_v1_test_workflow_template_proto_rawDesc), len(file_testkube_sync_v1_test_workflow_template_proto_rawDesc)))
	})
	return file_testkube_sync_v1_test_workflow_template_proto_rawDescData
}

var file_testkube_sync_v1_test_workflow_template_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testkube_sync_v1_test_workflow_template_proto_goTypes = []any{
	(*TestWorkflowTemplate)(nil), // 0: testkube.sync.v1.TestWorkflowTemplate
}
var file_testkube_sync_v1_test_workflow_template_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testkube_sync_v1_test_workflow_template_proto_init() }
func file_testkube_sync_v1_test_workflow_template_proto_init() {
	if File_testkube_sync_v1_test_workflow_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testkube_sync_v1_test_workflow_template_proto_rawDesc), len(file_testkube_sync_v1_test_workflow_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testkube_sync_v1_test_workflow_template_proto_goTypes,
		DependencyIndexes: file_testkube_sync_v1_test_workflow_template_proto_depIdxs,
		MessageInfos:      file_testkube_sync_v1_test_workflow_template_proto_msgTypes,
	}.Build()
	File_testkube_sync_v1_test_workflow_template_proto = out.File
	file_testkube_sync_v1_test_workflow_template_proto_goTypes = nil
	file_testkube_sync_v1_test_workflow_template_proto_depIdxs = nil
}
