// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testkube/sync/v1/update_or_create_request.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateOrCreateRequest is the message sent by a client when
// requesting the update or creation of a Testkube object.
type UpdateOrCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payload is the protobuf representation of the object that
	// has been modified in the Agent's observable scope.
	// The Payload that is used determines which type of object
	// is identified as modified.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UpdateOrCreateRequest_TestTrigger
	//	*UpdateOrCreateRequest_TestWorkflow
	//	*UpdateOrCreateRequest_TestWorkflowTemplate
	//	*UpdateOrCreateRequest_Webhook
	//	*UpdateOrCreateRequest_WebhookTemplate
	Payload       isUpdateOrCreateRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrCreateRequest) Reset() {
	*x = UpdateOrCreateRequest{}
	mi := &file_testkube_sync_v1_update_or_create_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrCreateRequest) ProtoMessage() {}

func (x *UpdateOrCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_sync_v1_update_or_create_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrCreateRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrCreateRequest) Descriptor() ([]byte, []int) {
	return file_testkube_sync_v1_update_or_create_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrCreateRequest) GetPayload() isUpdateOrCreateRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateOrCreateRequest) GetTestTrigger() *TestTrigger {
	if x != nil {
		if x, ok := x.Payload.(*UpdateOrCreateRequest_TestTrigger); ok {
			return x.TestTrigger
		}
	}
	return nil
}

func (x *UpdateOrCreateRequest) GetTestWorkflow() *TestWorkflow {
	if x != nil {
		if x, ok := x.Payload.(*UpdateOrCreateRequest_TestWorkflow); ok {
			return x.TestWorkflow
		}
	}
	return nil
}

func (x *UpdateOrCreateRequest) GetTestWorkflowTemplate() *TestWorkflowTemplate {
	if x != nil {
		if x, ok := x.Payload.(*UpdateOrCreateRequest_TestWorkflowTemplate); ok {
			return x.TestWorkflowTemplate
		}
	}
	return nil
}

func (x *UpdateOrCreateRequest) GetWebhook() *Webhook {
	if x != nil {
		if x, ok := x.Payload.(*UpdateOrCreateRequest_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

func (x *UpdateOrCreateRequest) GetWebhookTemplate() *WebhookTemplate {
	if x != nil {
		if x, ok := x.Payload.(*UpdateOrCreateRequest_WebhookTemplate); ok {
			return x.WebhookTemplate
		}
	}
	return nil
}

type isUpdateOrCreateRequest_Payload interface {
	isUpdateOrCreateRequest_Payload()
}

type UpdateOrCreateRequest_TestTrigger struct {
	// test_trigger indicates the object is a TestTrigger
	TestTrigger *TestTrigger `protobuf:"bytes,1,opt,name=test_trigger,json=testTrigger,oneof"`
}

type UpdateOrCreateRequest_TestWorkflow struct {
	// test_workflow indicates the object is a TestWorkflow
	TestWorkflow *TestWorkflow `protobuf:"bytes,2,opt,name=test_workflow,json=testWorkflow,oneof"`
}

type UpdateOrCreateRequest_TestWorkflowTemplate struct {
	// test_workflow_template indicates the object is a TestWorkflowTemplate
	TestWorkflowTemplate *TestWorkflowTemplate `protobuf:"bytes,3,opt,name=test_workflow_template,json=testWorkflowTemplate,oneof"`
}

type UpdateOrCreateRequest_Webhook struct {
	// webhook indicates the object is a Webhook
	Webhook *Webhook `protobuf:"bytes,4,opt,name=webhook,oneof"`
}

type UpdateOrCreateRequest_WebhookTemplate struct {
	// webhook_template indicates the object is a WebhookTemplate
	WebhookTemplate *WebhookTemplate `protobuf:"bytes,5,opt,name=webhook_template,json=webhookTemplate,oneof"`
}

func (*UpdateOrCreateRequest_TestTrigger) isUpdateOrCreateRequest_Payload() {}

func (*UpdateOrCreateRequest_TestWorkflow) isUpdateOrCreateRequest_Payload() {}

func (*UpdateOrCreateRequest_TestWorkflowTemplate) isUpdateOrCreateRequest_Payload() {}

func (*UpdateOrCreateRequest_Webhook) isUpdateOrCreateRequest_Payload() {}

func (*UpdateOrCreateRequest_WebhookTemplate) isUpdateOrCreateRequest_Payload() {}

var File_testkube_sync_v1_update_or_create_request_proto protoreflect.FileDescriptor

const file_testkube_sync_v1_update_or_create_request_proto_rawDesc = "" +
	"\n" +
	"/testkube/sync/v1/update_or_create_request.proto\x12\x10testkube.sync.v1\x1a#testkube/sync/v1/test_trigger.proto\x1a$testkube/sync/v1/test_workflow.proto\x1a-testkube/sync/v1/test_workflow_template.proto\x1a\x1etestkube/sync/v1/webhook.proto\x1a'testkube/sync/v1/webhook_template.proto\"\x94\x03\n" +
	"\x15UpdateOrCreateRequest\x12B\n" +
	"\ftest_trigger\x18\x01 \x01(\v2\x1d.testkube.sync.v1.TestTriggerH\x00R\vtestTrigger\x12E\n" +
	"\rtest_workflow\x18\x02 \x01(\v2\x1e.testkube.sync.v1.TestWorkflowH\x00R\ftestWorkflow\x12^\n" +
	"\x16test_workflow_template\x18\x03 \x01(\v2&.testkube.sync.v1.TestWorkflowTemplateH\x00R\x14testWorkflowTemplate\x125\n" +
	"\awebhook\x18\x04 \x01(\v2\x19.testkube.sync.v1.WebhookH\x00R\awebhook\x12N\n" +
	"\x10webhook_template\x18\x05 \x01(\v2!.testkube.sync.v1.WebhookTemplateH\x00R\x0fwebhookTemplateB\t\n" +
	"\apayloadB\xd4\x01\n" +
	"\x14com.testkube.sync.v1B\x1aUpdateOrCreateRequestProtoP\x01Z>github.com/kubeshop/testkube/pkg/proto/testkube/sync/v1;syncv1\xa2\x02\x03TSX\xaa\x02\x10Testkube.Sync.V1\xca\x02\x10Testkube\\Sync\\V1\xe2\x02\x1cTestkube\\Sync\\V1\\GPBMetadata\xea\x02\x12Testkube::Sync::V1b\beditionsp\xe8\a"

var (
	file_testkube_sync_v1_update_or_create_request_proto_rawDescOnce sync.Once
	file_testkube_sync_v1_update_or_create_request_proto_rawDescData []byte
)

func file_testkube_sync_v1_update_or_create_request_proto_rawDescGZIP() []byte {
	file_testkube_sync_v1_update_or_create_request_proto_rawDescOnce.Do(func() {
		file_testkube_sync_v1_update_or_create_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testkube_sync_v1_update_or_create_request_proto_rawDesc), len(file_testkube_sync_v1_update_or_create_request_proto_rawDesc)))
	})
	return file_testkube_sync_v1_update_or_create_request_proto_rawDescData
}

var file_testkube_sync_v1_update_or_create_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testkube_sync_v1_update_or_create_request_proto_goTypes = []any{
	(*UpdateOrCreateRequest)(nil), // 0: testkube.sync.v1.UpdateOrCreateRequest
	(*TestTrigger)(nil),           // 1: testkube.sync.v1.TestTrigger
	(*TestWorkflow)(nil),          // 2: testkube.sync.v1.TestWorkflow
	(*TestWorkflowTemplate)(nil),  // 3: testkube.sync.v1.TestWorkflowTemplate
	(*Webhook)(nil),               // 4: testkube.sync.v1.Webhook
	(*WebhookTemplate)(nil),       // 5: testkube.sync.v1.WebhookTemplate
}
var file_testkube_sync_v1_update_or_create_request_proto_depIdxs = []int32{
	1, // 0: testkube.sync.v1.UpdateOrCreateRequest.test_trigger:type_name -> testkube.sync.v1.TestTrigger
	2, // 1: testkube.sync.v1.UpdateOrCreateRequest.test_workflow:type_name -> testkube.sync.v1.TestWorkflow
	3, // 2: testkube.sync.v1.UpdateOrCreateRequest.test_workflow_template:type_name -> testkube.sync.v1.TestWorkflowTemplate
	4, // 3: testkube.sync.v1.UpdateOrCreateRequest.webhook:type_name -> testkube.sync.v1.Webhook
	5, // 4: testkube.sync.v1.UpdateOrCreateRequest.webhook_template:type_name -> testkube.sync.v1.WebhookTemplate
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_testkube_sync_v1_update_or_create_request_proto_init() }
func file_testkube_sync_v1_update_or_create_request_proto_init() {
	if File_testkube_sync_v1_update_or_create_request_proto != nil {
		return
	}
	file_testkube_sync_v1_test_trigger_proto_init()
	file_testkube_sync_v1_test_workflow_proto_init()
	file_testkube_sync_v1_test_workflow_template_proto_init()
	file_testkube_sync_v1_webhook_proto_init()
	file_testkube_sync_v1_webhook_template_proto_init()
	file_testkube_sync_v1_update_or_create_request_proto_msgTypes[0].OneofWrappers = []any{
		(*UpdateOrCreateRequest_TestTrigger)(nil),
		(*UpdateOrCreateRequest_TestWorkflow)(nil),
		(*UpdateOrCreateRequest_TestWorkflowTemplate)(nil),
		(*UpdateOrCreateRequest_Webhook)(nil),
		(*UpdateOrCreateRequest_WebhookTemplate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testkube_sync_v1_update_or_create_request_proto_rawDesc), len(file_testkube_sync_v1_update_or_create_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testkube_sync_v1_update_or_create_request_proto_goTypes,
		DependencyIndexes: file_testkube_sync_v1_update_or_create_request_proto_depIdxs,
		MessageInfos:      file_testkube_sync_v1_update_or_create_request_proto_msgTypes,
	}.Build()
	File_testkube_sync_v1_update_or_create_request_proto = out.File
	file_testkube_sync_v1_update_or_create_request_proto_goTypes = nil
	file_testkube_sync_v1_update_or_create_request_proto_depIdxs = nil
}
