package envsconst

const (
	EnvRunnerStorageEndpoint           = "RUNNER_STORAGE_ENDPOINT"
	EnvRunnerStorageAccessKeyID        = "RUNNER_STORAGE_ACCESSKEYID"
	EnvRunnerStorageSecretAccessKey    = "RUNNER_STORAGE_SECRETACCESSKEY"
	EnvRunnerStorageRegion             = "RUNNER_STORAGE_REGION"
	EnvRunnerStorageToken              = "RUNNER_STORAGE_TOKEN"
	EnvRunnerStorageBucket             = "RUNNER_STORAGE_BUCKET"
	EnvRunnerStorageSSL                = "RUNNER_STORAGE_SSL"
	EnvRunnerStorageSkipVerify         = "RUNNER_STORAGE_SKIP_VERIFY"
	EnvRunnerStorageCertFile           = "RUNNER_STORAGE_CERT_FILE"
	EnvRunnerStorageKeyFile            = "RUNNER_STORAGE_KEY_FILE"
	EnvRunnerStorageCAFile             = "RUNNER_STORAGE_CA_FILE"
	EnvRunnerScrapperEnabled           = "RUNNER_SCRAPPERENABLED"
	EnvRunnerDataDir                   = "RUNNER_DATADIR"
	EnvRunnerGitUsername               = "RUNNER_GITUSERNAME"
	EnvRunnerGitToken                  = "RUNNER_GITTOKEN"
	EnvRunnerCompressArtifacts         = "RUNNER_COMPRESSARTIFACTS"
	EnvRunnerWorkingDir                = "RUNNER_WORKINGDIR"
	EnvRunnerExecutionID               = "RUNNER_EXECUTIONID"
	EnvRunnerTestName                  = "RUNNER_TESTNAME"
	EnvRunnerExecutionNumber           = "RUNNER_EXECUTIONNUMBER"
	EnvRunnerContextType               = "RUNNER_CONTEXTTYPE"
	EnvRunnerContextData               = "RUNNER_CONTEXTDATA"
	EnvRunnerAPIURI                    = "RUNNER_APIURI"
	EnvRunnerClusterID                 = "RUNNER_CLUSTERID"
	EnvRunnerCDEventsTarget            = "RUNNER_CDEVENTS_TARGET"
	EnvRunnerDashboardURI              = "RUNNER_DASHBOARD_URI"
	EnvRunnerCloudMode                 = "RUNNER_CLOUD_MODE"
	EnvRunnerCloudAPIKey               = "RUNNER_CLOUD_API_KEY"
	EnvRunnerCloudAPIURL               = "RUNNER_CLOUD_API_URL"
	EnvRunnerAgentConnectionTimeoutSec = "RUNNER_CLOUD_CONNECTION_TIMEOUT"
	EnvRunnerAgentInsecure             = "RUNNER_AGENT_INSECURE"
	EnvRunnerAgentSkipVerify           = "RUNNER_AGENT_SKIP_VERIFY"
	EnvRunnerAgentCertFile             = "RUNNER_AGENT_CERT_FILE"
	EnvRunnerAgentKeyFile              = "RUNNER_AGENT_KEY_FILE"
	EnvRunnerAgentCAFile               = "RUNNER_AGENT_CA_FILE"
	EnvRunnerSlavesConfigs             = "RUNNER_SLAVES_CONFIGS"
	EnvSlavesCount                     = "SLAVES_COUNT"
)
