{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-logs.serviceAccountName" . }}
  labels:
    {{- include "global.labels.standard" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.annotations }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}

{{- if .Values.testServiceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-logs.testServiceAccountName" . }}
  labels:
    {{- include "global.labels.standard" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.annotations }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
