// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube/pkg/operator/client/testsuites/v2 (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=./mock_testsuites.go -package=v2 github.com/kubeshop/testkube/pkg/operator/client/testsuites/v2 Interface
//

// Package v2 is a generated GoMock package.
package v2

import (
	reflect "reflect"

	v2 "github.com/kubeshop/testkube/api/testsuite/v2"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInterface) Create(testsuite *v2.TestSuite) (*v2.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", testsuite)
	ret0, _ := ret[0].(*v2.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInterfaceMockRecorder) Create(testsuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterface)(nil).Create), testsuite)
}

// CreateTestsuiteSecrets mocks base method.
func (m *MockInterface) CreateTestsuiteSecrets(testsuite *v2.TestSuite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestsuiteSecrets", testsuite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTestsuiteSecrets indicates an expected call of CreateTestsuiteSecrets.
func (mr *MockInterfaceMockRecorder) CreateTestsuiteSecrets(testsuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestsuiteSecrets", reflect.TypeOf((*MockInterface)(nil).CreateTestsuiteSecrets), testsuite)
}

// Delete mocks base method.
func (m *MockInterface) Delete(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfaceMockRecorder) Delete(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterface)(nil).Delete), name)
}

// DeleteAll mocks base method.
func (m *MockInterface) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockInterfaceMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockInterface)(nil).DeleteAll))
}

// DeleteByLabels mocks base method.
func (m *MockInterface) DeleteByLabels(selector string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLabels", selector)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByLabels indicates an expected call of DeleteByLabels.
func (mr *MockInterfaceMockRecorder) DeleteByLabels(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLabels", reflect.TypeOf((*MockInterface)(nil).DeleteByLabels), selector)
}

// Get mocks base method.
func (m *MockInterface) Get(name string) (*v2.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*v2.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfaceMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterface)(nil).Get), name)
}

// GetCurrentSecretUUID mocks base method.
func (m *MockInterface) GetCurrentSecretUUID(testSuiteName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSecretUUID", testSuiteName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSecretUUID indicates an expected call of GetCurrentSecretUUID.
func (mr *MockInterfaceMockRecorder) GetCurrentSecretUUID(testSuiteName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSecretUUID", reflect.TypeOf((*MockInterface)(nil).GetCurrentSecretUUID), testSuiteName)
}

// GetSecretTestSuiteVars mocks base method.
func (m *MockInterface) GetSecretTestSuiteVars(testSuiteName, secretUUID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretTestSuiteVars", testSuiteName, secretUUID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretTestSuiteVars indicates an expected call of GetSecretTestSuiteVars.
func (mr *MockInterfaceMockRecorder) GetSecretTestSuiteVars(testSuiteName, secretUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretTestSuiteVars", reflect.TypeOf((*MockInterface)(nil).GetSecretTestSuiteVars), testSuiteName, secretUUID)
}

// List mocks base method.
func (m *MockInterface) List(selector string) (*v2.TestSuiteList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].(*v2.TestSuiteList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInterfaceMockRecorder) List(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInterface)(nil).List), selector)
}

// ListLabels mocks base method.
func (m *MockInterface) ListLabels() (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels")
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockInterfaceMockRecorder) ListLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockInterface)(nil).ListLabels))
}

// LoadTestsuiteVariablesSecret mocks base method.
func (m *MockInterface) LoadTestsuiteVariablesSecret(testsuite *v2.TestSuite) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTestsuiteVariablesSecret", testsuite)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTestsuiteVariablesSecret indicates an expected call of LoadTestsuiteVariablesSecret.
func (mr *MockInterfaceMockRecorder) LoadTestsuiteVariablesSecret(testsuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTestsuiteVariablesSecret", reflect.TypeOf((*MockInterface)(nil).LoadTestsuiteVariablesSecret), testsuite)
}

// Update mocks base method.
func (m *MockInterface) Update(testsuite *v2.TestSuite) (*v2.TestSuite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", testsuite)
	ret0, _ := ret[0].(*v2.TestSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInterfaceMockRecorder) Update(testsuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterface)(nil).Update), testsuite)
}

// UpdateStatus mocks base method.
func (m *MockInterface) UpdateStatus(testSuite *v2.TestSuite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", testSuite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockInterfaceMockRecorder) UpdateStatus(testSuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockInterface)(nil).UpdateStatus), testSuite)
}

// UpdateTestsuiteSecrets mocks base method.
func (m *MockInterface) UpdateTestsuiteSecrets(testsuite *v2.TestSuite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTestsuiteSecrets", testsuite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTestsuiteSecrets indicates an expected call of UpdateTestsuiteSecrets.
func (mr *MockInterfaceMockRecorder) UpdateTestsuiteSecrets(testsuite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTestsuiteSecrets", reflect.TypeOf((*MockInterface)(nil).UpdateTestsuiteSecrets), testsuite)
}
