// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testkube/testworkflow/execution/v1/accept_execution_request.proto

package executionv1

import (
	v1 "github.com/kubeshop/testkube/pkg/proto/testkube/testworkflow/signature/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AcceptExecutionRequest is a request to the Control Plane to indicate that a Test
// Workflow Execution has been sent to Kubernetes and is awaiting scheduling by the
// Kubernetes scheduler. It includes fields that are relevant for the Control Plane
// but which could not have been known before this point in time.
type AcceptExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier of the execution that is scheduling.
	ExecutionId *string `protobuf:"bytes,1,opt,name=execution_id,json=executionId" json:"execution_id,omitempty"`
	// namespace is the Kubernetes namespace into which the execution is being scheduled.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// signature is an internal representation of the steps of the workflow that will be
	// executed by the execution. It should be passed here as it is not until this point
	// that it is possible to guarantee the state of the workflow that will be executed.
	Signature     []*v1.Signature `protobuf:"bytes,3,rep,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptExecutionRequest) Reset() {
	*x = AcceptExecutionRequest{}
	mi := &file_testkube_testworkflow_execution_v1_accept_execution_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptExecutionRequest) ProtoMessage() {}

func (x *AcceptExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_accept_execution_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptExecutionRequest.ProtoReflect.Descriptor instead.
func (*AcceptExecutionRequest) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptExecutionRequest) GetExecutionId() string {
	if x != nil && x.ExecutionId != nil {
		return *x.ExecutionId
	}
	return ""
}

func (x *AcceptExecutionRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *AcceptExecutionRequest) GetSignature() []*v1.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_testkube_testworkflow_execution_v1_accept_execution_request_proto protoreflect.FileDescriptor

const file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDesc = "" +
	"\n" +
	"Atestkube/testworkflow/execution/v1/accept_execution_request.proto\x12\"testkube.testworkflow.execution.v1\x1a2testkube/testworkflow/signature/v1/signature.proto\"\xa6\x01\n" +
	"\x16AcceptExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12K\n" +
	"\tsignature\x18\x03 \x03(\v2-.testkube.testworkflow.signature.v1.SignatureR\tsignatureB\xc7\x02\n" +
	"&com.testkube.testworkflow.execution.v1B\x1bAcceptExecutionRequestProtoP\x01ZUgithub.com/kubeshop/testkube/pkg/proto/testkube/testworkflow/execution/v1;executionv1\xa2\x02\x03TTE\xaa\x02\"Testkube.Testworkflow.Execution.V1\xca\x02\"Testkube\\Testworkflow\\Execution\\V1\xe2\x02.Testkube\\Testworkflow\\Execution\\V1\\GPBMetadata\xea\x02%Testkube::Testworkflow::Execution::V1b\beditionsp\xe8\a"

var (
	file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescOnce sync.Once
	file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescData []byte
)

func file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescGZIP() []byte {
	file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescOnce.Do(func() {
		file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDesc)))
	})
	return file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDescData
}

var file_testkube_testworkflow_execution_v1_accept_execution_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testkube_testworkflow_execution_v1_accept_execution_request_proto_goTypes = []any{
	(*AcceptExecutionRequest)(nil), // 0: testkube.testworkflow.execution.v1.AcceptExecutionRequest
	(*v1.Signature)(nil),           // 1: testkube.testworkflow.signature.v1.Signature
}
var file_testkube_testworkflow_execution_v1_accept_execution_request_proto_depIdxs = []int32{
	1, // 0: testkube.testworkflow.execution.v1.AcceptExecutionRequest.signature:type_name -> testkube.testworkflow.signature.v1.Signature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testkube_testworkflow_execution_v1_accept_execution_request_proto_init() }
func file_testkube_testworkflow_execution_v1_accept_execution_request_proto_init() {
	if File_testkube_testworkflow_execution_v1_accept_execution_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_accept_execution_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testkube_testworkflow_execution_v1_accept_execution_request_proto_goTypes,
		DependencyIndexes: file_testkube_testworkflow_execution_v1_accept_execution_request_proto_depIdxs,
		MessageInfos:      file_testkube_testworkflow_execution_v1_accept_execution_request_proto_msgTypes,
	}.Build()
	File_testkube_testworkflow_execution_v1_accept_execution_request_proto = out.File
	file_testkube_testworkflow_execution_v1_accept_execution_request_proto_goTypes = nil
	file_testkube_testworkflow_execution_v1_accept_execution_request_proto_depIdxs = nil
}
