// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testkube/testworkflow/execution/v1/execution_lineage.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionLineage records where a rerun came from, so that a workflow can read
// the run it descends from and a reader can follow the chain back to its origin.
//
// Recorded on every execution, which is what makes the reserved
// `execution("rerun")` reference resolve inside the pod after any rerun.
//
// Derived by the Control Plane from the base execution rather than supplied: a
// caller able to assert a root or an attempt number could forge a chain.
type ExecutionLineage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base_execution_id is the execution this one is a rerun of. Empty for an
	// original run.
	BaseExecutionId *string `protobuf:"bytes,1,opt,name=base_execution_id,json=baseExecutionId" json:"base_execution_id,omitempty"`
	// root_execution_id is the first execution in the chain. An original run is
	// its own root, so that every execution of a chain shares one value here.
	RootExecutionId *string `protobuf:"bytes,2,opt,name=root_execution_id,json=rootExecutionId" json:"root_execution_id,omitempty"`
	// attempt is 1 for an original run, and one more than the base's for a rerun.
	Attempt       *int32 `protobuf:"varint,3,opt,name=attempt" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLineage) Reset() {
	*x = ExecutionLineage{}
	mi := &file_testkube_testworkflow_execution_v1_execution_lineage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLineage) ProtoMessage() {}

func (x *ExecutionLineage) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_execution_lineage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLineage.ProtoReflect.Descriptor instead.
func (*ExecutionLineage) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionLineage) GetBaseExecutionId() string {
	if x != nil && x.BaseExecutionId != nil {
		return *x.BaseExecutionId
	}
	return ""
}

func (x *ExecutionLineage) GetRootExecutionId() string {
	if x != nil && x.RootExecutionId != nil {
		return *x.RootExecutionId
	}
	return ""
}

func (x *ExecutionLineage) GetAttempt() int32 {
	if x != nil && x.Attempt != nil {
		return *x.Attempt
	}
	return 0
}

var File_testkube_testworkflow_execution_v1_execution_lineage_proto protoreflect.FileDescriptor

const file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDesc = "" +
	"\n" +
	":testkube/testworkflow/execution/v1/execution_lineage.proto\x12\"testkube.testworkflow.execution.v1\"\x84\x01\n" +
	"\x10ExecutionLineage\x12*\n" +
	"\x11base_execution_id\x18\x01 \x01(\tR\x0fbaseExecutionId\x12*\n" +
	"\x11root_execution_id\x18\x02 \x01(\tR\x0frootExecutionId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattemptB\xc1\x02\n" +
	"&com.testkube.testworkflow.execution.v1B\x15ExecutionLineageProtoP\x01ZUgithub.com/kubeshop/testkube/pkg/proto/testkube/testworkflow/execution/v1;executionv1\xa2\x02\x03TTE\xaa\x02\"Testkube.Testworkflow.Execution.V1\xca\x02\"Testkube\\Testworkflow\\Execution\\V1\xe2\x02.Testkube\\Testworkflow\\Execution\\V1\\GPBMetadata\xea\x02%Testkube::Testworkflow::Execution::V1b\beditionsp\xe8\a"

var (
	file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescOnce sync.Once
	file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescData []byte
)

func file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescGZIP() []byte {
	file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescOnce.Do(func() {
		file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDesc)))
	})
	return file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDescData
}

var file_testkube_testworkflow_execution_v1_execution_lineage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testkube_testworkflow_execution_v1_execution_lineage_proto_goTypes = []any{
	(*ExecutionLineage)(nil), // 0: testkube.testworkflow.execution.v1.ExecutionLineage
}
var file_testkube_testworkflow_execution_v1_execution_lineage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testkube_testworkflow_execution_v1_execution_lineage_proto_init() }
func file_testkube_testworkflow_execution_v1_execution_lineage_proto_init() {
	if File_testkube_testworkflow_execution_v1_execution_lineage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_execution_lineage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testkube_testworkflow_execution_v1_execution_lineage_proto_goTypes,
		DependencyIndexes: file_testkube_testworkflow_execution_v1_execution_lineage_proto_depIdxs,
		MessageInfos:      file_testkube_testworkflow_execution_v1_execution_lineage_proto_msgTypes,
	}.Build()
	File_testkube_testworkflow_execution_v1_execution_lineage_proto = out.File
	file_testkube_testworkflow_execution_v1_execution_lineage_proto_goTypes = nil
	file_testkube_testworkflow_execution_v1_execution_lineage_proto_depIdxs = nil
}
