apiVersion: v2
name: testkube-runner
description: A Helm chart for the Testkube's Runner Agent
type: application
version: 2.7.2
appVersion: 2.7.2
dependencies:
- name: global
  version: 0.x.x-x
  repository: "file://../global"
- name: testkube-crds
  version: 0.1.0
  repository: "file://../testkube-crds"
