// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube/pkg/newclients/workflowtriggerclient (interfaces: WorkflowTriggerClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_interface.go -package=workflowtriggerclient github.com/kubeshop/testkube/pkg/newclients/workflowtriggerclient WorkflowTriggerClient
//

// Package workflowtriggerclient is a generated GoMock package.
package workflowtriggerclient

import (
	context "context"
	reflect "reflect"

	testkube "github.com/kubeshop/testkube/pkg/api/v1/testkube"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowTriggerClient is a mock of WorkflowTriggerClient interface.
type MockWorkflowTriggerClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowTriggerClientMockRecorder
	isgomock struct{}
}

// MockWorkflowTriggerClientMockRecorder is the mock recorder for MockWorkflowTriggerClient.
type MockWorkflowTriggerClientMockRecorder struct {
	mock *MockWorkflowTriggerClient
}

// NewMockWorkflowTriggerClient creates a new mock instance.
func NewMockWorkflowTriggerClient(ctrl *gomock.Controller) *MockWorkflowTriggerClient {
	mock := &MockWorkflowTriggerClient{ctrl: ctrl}
	mock.recorder = &MockWorkflowTriggerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowTriggerClient) EXPECT() *MockWorkflowTriggerClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowTriggerClient) Create(ctx context.Context, environmentId string, trigger testkube.WorkflowTrigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, environmentId, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowTriggerClientMockRecorder) Create(ctx, environmentId, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).Create), ctx, environmentId, trigger)
}

// Delete mocks base method.
func (m *MockWorkflowTriggerClient) Delete(ctx context.Context, environmentId, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, environmentId, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowTriggerClientMockRecorder) Delete(ctx, environmentId, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).Delete), ctx, environmentId, name, namespace)
}

// DeleteAll mocks base method.
func (m *MockWorkflowTriggerClient) DeleteAll(ctx context.Context, environmentId, namespace string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, environmentId, namespace)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockWorkflowTriggerClientMockRecorder) DeleteAll(ctx, environmentId, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).DeleteAll), ctx, environmentId, namespace)
}

// DeleteByLabels mocks base method.
func (m *MockWorkflowTriggerClient) DeleteByLabels(ctx context.Context, environmentId, selector, namespace string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByLabels", ctx, environmentId, selector, namespace)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByLabels indicates an expected call of DeleteByLabels.
func (mr *MockWorkflowTriggerClientMockRecorder) DeleteByLabels(ctx, environmentId, selector, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByLabels", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).DeleteByLabels), ctx, environmentId, selector, namespace)
}

// Get mocks base method.
func (m *MockWorkflowTriggerClient) Get(ctx context.Context, environmentId, name, namespace string) (*testkube.WorkflowTrigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, environmentId, name, namespace)
	ret0, _ := ret[0].(*testkube.WorkflowTrigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkflowTriggerClientMockRecorder) Get(ctx, environmentId, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).Get), ctx, environmentId, name, namespace)
}

// List mocks base method.
func (m *MockWorkflowTriggerClient) List(ctx context.Context, environmentId string, options ListOptions, namespace string) ([]testkube.WorkflowTrigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, environmentId, options, namespace)
	ret0, _ := ret[0].([]testkube.WorkflowTrigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowTriggerClientMockRecorder) List(ctx, environmentId, options, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).List), ctx, environmentId, options, namespace)
}

// Update mocks base method.
func (m *MockWorkflowTriggerClient) Update(ctx context.Context, environmentId string, trigger testkube.WorkflowTrigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, environmentId, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowTriggerClientMockRecorder) Update(ctx, environmentId, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowTriggerClient)(nil).Update), ctx, environmentId, trigger)
}
