// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: testkube/testworkflow/execution/v1/execution.proto

package executionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutionState is a type used to indicate states of Test Workflow Executions.
type ExecutionState int32

const (
	// EXECUTION_STATE_UNSPECIFIED an unknown state is provided, no action should be taken.
	ExecutionState_EXECUTION_STATE_UNSPECIFIED ExecutionState = 0
	// EXECUTION_STATE_RUNNING to transition to this state the Execution should be either:
	// - Started if the Execution is currently Queued, Pending, or has no state set.
	// - Resumed if the Execution is currently Paused.
	ExecutionState_EXECUTION_STATE_RUNNING ExecutionState = 1
	// EXECUTION_STATE_PAUSED, to transition to this state the Execution should be paused.
	ExecutionState_EXECUTION_STATE_PAUSED ExecutionState = 2
	// EXECUTION_STATE_CANCELLED, to transition to this state the Execution should be gracefully
	// stopped and once the stop is complete the Control Plane should be updated
	// that the Execution has been successfully cancelled.
	ExecutionState_EXECUTION_STATE_CANCELLED ExecutionState = 3
	// EXECUTION_STATE_ABORTED, to transition to this state the Execution should be first gracefully
	// stopped, however if this fails the Execution can be forcefully stopped.
	// If the state transition is successful, or has failed after forceful stop is attempted
	// then the Control Plane should be updated that the Execution has been aborted.
	// It is understood that this process can leave "floating", "orphaned", or "zombie"
	// Execution related resources.
	ExecutionState_EXECUTION_STATE_ABORTED ExecutionState = 4
)

// Enum value maps for ExecutionState.
var (
	ExecutionState_name = map[int32]string{
		0: "EXECUTION_STATE_UNSPECIFIED",
		1: "EXECUTION_STATE_RUNNING",
		2: "EXECUTION_STATE_PAUSED",
		3: "EXECUTION_STATE_CANCELLED",
		4: "EXECUTION_STATE_ABORTED",
	}
	ExecutionState_value = map[string]int32{
		"EXECUTION_STATE_UNSPECIFIED": 0,
		"EXECUTION_STATE_RUNNING":     1,
		"EXECUTION_STATE_PAUSED":      2,
		"EXECUTION_STATE_CANCELLED":   3,
		"EXECUTION_STATE_ABORTED":     4,
	}
)

func (x ExecutionState) Enum() *ExecutionState {
	p := new(ExecutionState)
	*p = x
	return p
}

func (x ExecutionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionState) Descriptor() protoreflect.EnumDescriptor {
	return file_testkube_testworkflow_execution_v1_execution_proto_enumTypes[0].Descriptor()
}

func (ExecutionState) Type() protoreflect.EnumType {
	return &file_testkube_testworkflow_execution_v1_execution_proto_enumTypes[0]
}

func (x ExecutionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionState.Descriptor instead.
func (ExecutionState) EnumDescriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

// GetExecutionUpdatesRequest is currently empty but remains reserved for future usage
// without breaking backwards proto compatibility.
// https://buf.build/docs/best-practices/style-guide/#rpc-use-empty
// Information used to select Execution information to return is expected to be provided
// using message headers including Organization, Environment, and Agent identifiers and
// authorization tokens.
type GetExecutionUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionUpdatesRequest) Reset() {
	*x = GetExecutionUpdatesRequest{}
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionUpdatesRequest) ProtoMessage() {}

func (x *GetExecutionUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP(), []int{0}
}

// ExecutionStart contains fields used to initially start an Execution.
type ExecutionStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier of the execution to be started.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// environment_id is the unique identifier of the environment in which the execution should be started.
	EnvironmentId string `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// execution_token is an authentication token that can be used to obtain any required
	// additional information about an execution from the Control Plane.
	ExecutionToken *string `protobuf:"bytes,3,opt,name=execution_token,json=executionToken,proto3,oneof" json:"execution_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionStart) Reset() {
	*x = ExecutionStart{}
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStart) ProtoMessage() {}

func (x *ExecutionStart) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStart.ProtoReflect.Descriptor instead.
func (*ExecutionStart) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionStart) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionStart) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ExecutionStart) GetExecutionToken() string {
	if x != nil && x.ExecutionToken != nil {
		return *x.ExecutionToken
	}
	return ""
}

// ExecutionStateTransition contains fields used to transition an execution to a new state.
type ExecutionStateTransition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// execution_id is the unique identifier of the execution to be transitioned.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// transition_to is the state the execution should be transitioned into.
	TransitionTo  ExecutionState `protobuf:"varint,2,opt,name=transition_to,json=transitionTo,proto3,enum=testkube.testworkflow.execution.v1.ExecutionState" json:"transition_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStateTransition) Reset() {
	*x = ExecutionStateTransition{}
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStateTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStateTransition) ProtoMessage() {}

func (x *ExecutionStateTransition) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStateTransition.ProtoReflect.Descriptor instead.
func (*ExecutionStateTransition) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionStateTransition) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionStateTransition) GetTransitionTo() ExecutionState {
	if x != nil {
		return x.TransitionTo
	}
	return ExecutionState_EXECUTION_STATE_UNSPECIFIED
}

// GetExecutionUpdatesResponse is the Control Plane response to a request for execution state
// transitions that should be performed by the client.
type GetExecutionUpdatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start may or may not be included and indicates an Execution that should be started.
	// A maximum of one execution to start is expected for each call to the RPC, rapid calls
	// to the RPC without informing the Control Plane that the Execution is successfully started
	// are expected to yield the same Execution and so clients SHOULD NOT call the RPC again
	// until the Execution has been successfully started, or periodically if no Execution was
	// returned.
	Start *ExecutionStart `protobuf:"bytes,1,opt,name=start,proto3,oneof" json:"start,omitempty"`
	// update lists all Executions understood to be under the control of the client that should
	// have their state transitioned. Subsequent calls to the RPC will yield duplicate updates
	// if the Execution state transition successes have not been communicated to the Control
	// Plane, however new state transition directives may be added in the interim so it is not
	// expected that a client would wait to successfully transition all Executions before calling
	// the RPC again, instead clients should interpret duplicate state transitions in a sensible
	// manner to prevent overloading Execution state transition behaviour.
	Update        []*ExecutionStateTransition `protobuf:"bytes,2,rep,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionUpdatesResponse) Reset() {
	*x = GetExecutionUpdatesResponse{}
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionUpdatesResponse) ProtoMessage() {}

func (x *GetExecutionUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *GetExecutionUpdatesResponse) GetStart() *ExecutionStart {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetExecutionUpdatesResponse) GetUpdate() []*ExecutionStateTransition {
	if x != nil {
		return x.Update
	}
	return nil
}

var File_testkube_testworkflow_execution_v1_execution_proto protoreflect.FileDescriptor

const file_testkube_testworkflow_execution_v1_execution_proto_rawDesc = "" +
	"\n" +
	"2testkube/testworkflow/execution/v1/execution.proto\x12\"testkube.testworkflow.execution.v1\"\x1c\n" +
	"\x1aGetExecutionUpdatesRequest\"\x9c\x01\n" +
	"\x0eExecutionStart\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12,\n" +
	"\x0fexecution_token\x18\x03 \x01(\tH\x00R\x0eexecutionToken\x88\x01\x01B\x12\n" +
	"\x10_execution_token\"\x96\x01\n" +
	"\x18ExecutionStateTransition\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12W\n" +
	"\rtransition_to\x18\x02 \x01(\x0e22.testkube.testworkflow.execution.v1.ExecutionStateR\ftransitionTo\"\xcc\x01\n" +
	"\x1bGetExecutionUpdatesResponse\x12M\n" +
	"\x05start\x18\x01 \x01(\v22.testkube.testworkflow.execution.v1.ExecutionStartH\x00R\x05start\x88\x01\x01\x12T\n" +
	"\x06update\x18\x02 \x03(\v2<.testkube.testworkflow.execution.v1.ExecutionStateTransitionR\x06updateB\b\n" +
	"\x06_start*\xa6\x01\n" +
	"\x0eExecutionState\x12\x1f\n" +
	"\x1bEXECUTION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_STATE_RUNNING\x10\x01\x12\x1a\n" +
	"\x16EXECUTION_STATE_PAUSED\x10\x02\x12\x1d\n" +
	"\x19EXECUTION_STATE_CANCELLED\x10\x03\x12\x1b\n" +
	"\x17EXECUTION_STATE_ABORTED\x10\x042\xb7\x01\n" +
	"\x1cTestWorkflowExecutionService\x12\x96\x01\n" +
	"\x13GetExecutionUpdates\x12>.testkube.testworkflow.execution.v1.GetExecutionUpdatesRequest\x1a?.testkube.testworkflow.execution.v1.GetExecutionUpdatesResponseB\xba\x02\n" +
	"&com.testkube.testworkflow.execution.v1B\x0eExecutionProtoP\x01ZUgithub.com/kubeshop/testkube/pkg/cloud/testkube/testworkflow/execution/v1;executionv1\xa2\x02\x03TTE\xaa\x02\"Testkube.Testworkflow.Execution.V1\xca\x02\"Testkube\\Testworkflow\\Execution\\V1\xe2\x02.Testkube\\Testworkflow\\Execution\\V1\\GPBMetadata\xea\x02%Testkube::Testworkflow::Execution::V1b\x06proto3"

var (
	file_testkube_testworkflow_execution_v1_execution_proto_rawDescOnce sync.Once
	file_testkube_testworkflow_execution_v1_execution_proto_rawDescData []byte
)

func file_testkube_testworkflow_execution_v1_execution_proto_rawDescGZIP() []byte {
	file_testkube_testworkflow_execution_v1_execution_proto_rawDescOnce.Do(func() {
		file_testkube_testworkflow_execution_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_execution_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_execution_proto_rawDesc)))
	})
	return file_testkube_testworkflow_execution_v1_execution_proto_rawDescData
}

var file_testkube_testworkflow_execution_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testkube_testworkflow_execution_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testkube_testworkflow_execution_v1_execution_proto_goTypes = []any{
	(ExecutionState)(0),                 // 0: testkube.testworkflow.execution.v1.ExecutionState
	(*GetExecutionUpdatesRequest)(nil),  // 1: testkube.testworkflow.execution.v1.GetExecutionUpdatesRequest
	(*ExecutionStart)(nil),              // 2: testkube.testworkflow.execution.v1.ExecutionStart
	(*ExecutionStateTransition)(nil),    // 3: testkube.testworkflow.execution.v1.ExecutionStateTransition
	(*GetExecutionUpdatesResponse)(nil), // 4: testkube.testworkflow.execution.v1.GetExecutionUpdatesResponse
}
var file_testkube_testworkflow_execution_v1_execution_proto_depIdxs = []int32{
	0, // 0: testkube.testworkflow.execution.v1.ExecutionStateTransition.transition_to:type_name -> testkube.testworkflow.execution.v1.ExecutionState
	2, // 1: testkube.testworkflow.execution.v1.GetExecutionUpdatesResponse.start:type_name -> testkube.testworkflow.execution.v1.ExecutionStart
	3, // 2: testkube.testworkflow.execution.v1.GetExecutionUpdatesResponse.update:type_name -> testkube.testworkflow.execution.v1.ExecutionStateTransition
	1, // 3: testkube.testworkflow.execution.v1.TestWorkflowExecutionService.GetExecutionUpdates:input_type -> testkube.testworkflow.execution.v1.GetExecutionUpdatesRequest
	4, // 4: testkube.testworkflow.execution.v1.TestWorkflowExecutionService.GetExecutionUpdates:output_type -> testkube.testworkflow.execution.v1.GetExecutionUpdatesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_testkube_testworkflow_execution_v1_execution_proto_init() }
func file_testkube_testworkflow_execution_v1_execution_proto_init() {
	if File_testkube_testworkflow_execution_v1_execution_proto != nil {
		return
	}
	file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[1].OneofWrappers = []any{}
	file_testkube_testworkflow_execution_v1_execution_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testkube_testworkflow_execution_v1_execution_proto_rawDesc), len(file_testkube_testworkflow_execution_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testkube_testworkflow_execution_v1_execution_proto_goTypes,
		DependencyIndexes: file_testkube_testworkflow_execution_v1_execution_proto_depIdxs,
		EnumInfos:         file_testkube_testworkflow_execution_v1_execution_proto_enumTypes,
		MessageInfos:      file_testkube_testworkflow_execution_v1_execution_proto_msgTypes,
	}.Build()
	File_testkube_testworkflow_execution_v1_execution_proto = out.File
	file_testkube_testworkflow_execution_v1_execution_proto_goTypes = nil
	file_testkube_testworkflow_execution_v1_execution_proto_depIdxs = nil
}
