{{- if and .Values.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-operator.serviceAccountName" . }}
  namespace: {{ include "testkube-operator.namespace" . }}
  labels:
    {{- include "testkube-operator.labels" . | nindent 4 }}
  {{- if .Values.global.labels }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.global.annotations }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.enabled (and .Values.webhook.enabled .Values.webhook.patch.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-operator.webhook.serviceAccountName" . }}
  namespace: {{ include "testkube-operator.namespace" . }}
  labels:
    {{- include "testkube-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.webhook.patch.serviceAccount.annotations }}
    {{- toYaml .Values.webhook.patch.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.global.annotations }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
