# Default values for testkube-logs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

### @section  Global image parameters
## Important! Please, note that this will override sub-chart image parameters.
## Global Docker image registry
## Global Docker registry secret names as an array
global:
  # -- Global Docker image registry
  imageRegistry: ""
  # -- Global Docker registry secret names as an array
  imagePullSecrets: []
  # -- Labels to add to all deployed objects
  labels: {}
  # -- Annotations to add to all deployed objects
  annotations: {}
  # -- Node labels to add to all deployed Pods
  nodeSelector: {}
  # -- Affinity rules to add to all deployed Pods
  affinity: {}
  # -- Tolerations to add to all deployed pods
  tolerations: []
  # -- Global security Context for all containers
  containerSecurityContext: {}
  # -- Global security Context for all pods
  podSecurityContext: {}
  # -- Global pdb
  podDisruptionBudget:
    enabled: false

debug: true

pro:
  ## URL of the Cloud Saas Control Plane
  url: "logs.testkube.io:443"
  uiUrl: ""
  ## License Key
  key: ""
  ## Organization ID
  orgId: ""
  ## Environment ID
  envId: ""
  tls:
    ## Toggle should the connection to Agent API in Cloud/Enterprise use secure GRPC (GRPCS) (if false, it will use insecure GRPC)
    enabled: true
    ## Toggle should the client skip verifying the Agent API server cert in Cloud/Enterprise
    skipVerify: false
  ## Retrieve cloud information from existing secret
  existingSecret:
    ## Name of the secret. If set, this will be used instead of the above values
    name: ""
    ## Key for the License Key
    key: ""
    ## Key for the Organization ID
    orgId: ""
    ## Key for the Environment ID
    envId: ""

### @section Common parameters
## Kubernetes version (using Helm capabilities if not set)
kubeVersion: ""

## Number of Testkube Logs Pod replicas
replicaCount: 3

## Testkube Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

## Extra labels for Testkube API pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

### @section Specific parameters
## image.registry Testkube Logs image registry
## image.repository Testkube Logs image name
## image.tag Testkube Logs image tag
## image.digest Testkube Logs image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## image.pullPolicy Testkube Logs Image pull policy
## image.secret k8s secret for private registries
image:
  registry: docker.io
  repository: kubeshop/testkube-logs-server
  pullPolicy: IfNotPresent
  tag: "latest"
  digest: ""
  pullSecret: []

## Chart parameters
## nameOverride Overrides Chart name
## fullnameOverride Full name that overrides Chart name
nameOverride: ""
fullnameOverride: ""

## Service Account parameters
serviceAccount:
  ## Specifies whether a service account should be created
  create: true
  ## Annotations to add to the service account
  annotations: {}
  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  name: ""

## Test Job ServiceAccount parameters
testServiceAccount:
  ## Specifies whether a service account should be created
  create: true
  ## Annotations to add to the service account
  annotations: {}

## Test Job ServiceAccount name
jobServiceAccountName: ""

## Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}

## Configure Container Security Context for Testkube Logs
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
securityContext: {}

## Service parameters
service:
  ## Adapter service type
  type: ClusterIP
  ## HTTP Hostname
  httpHostname: ""
  ## HTTP Port
  httpPort: 8080
  ## GRPC Hostname
  grpcHostname: ""
  ## GRPC Port
  grpcPort: 9090
  ## Annotations
  annotations: {}
  ## Service labels
  labels: {}

## Testkube Logs Deployment parameters
## Dependecy to NATS
nats:
  ## URI that testkube logs uses to connect to NATS
  uri: "nats://testkube-nats"

tls:
  # -- Toggle whether to enable TLS in GRPC server
  enabled: false
  # -- Toggle whether to require client auth
  clientAuth: false
  # -- If enabled, will also require a client CA certificate to be provided
  mountClientCACertificate: false
  certSecret:
    # -- Toggle whether to mount k8s secret which contains GRPC server certificate (cert.crt, cert.key, client_ca.crt)
    enabled: false
    # -- Name of the grpc server certificate secret
    name: "grpc-server-cert"
    # -- Base path to mount the server certificate secret
    baseMountPath: /etc/server-certs/grpc
    # -- Path to server certificate file
    certFile: "cert.crt"
    # -- Path to server certificate key file
    keyFile: "cert.key"
    # -- Path to cliebt ca file (used for self-signed certificates)
    clientCAFile: "client_ca.crt"

## Extra Environment Variables which will be injected into the Testkube Logs container
extraEnvVars: {}
# - name: FOO
#   value: BAR

## Testkube Logs resource requests and limits
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Autoscaling parameters
## Enable autoscaling for Testkube API deployment
## Add custom labels to autoscaling
## Add custom annotations to autoscaling
## Minimum number of replicas to scale back
## Maximum number of replicas to scale out
## Target CPU utilization percentage
## Target Memory utilization percentage
autoscaling:
  enabled: true
  labels: {}
  annotations: {}
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## Node labels for Testkube Logs pod assignment.
nodeSelector: {}

## Tolerations for Testkube Logs  assignment.
tolerations: []

## Affinity for Testkube API Logs assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
affinity: {}

## Specify priorityClassName for Testkube Logs Deployment
priorityClassName: ""

## -- Test Connection pod
testConnection:
  enabled: false

storage:
  # -- MinIO endpoint
  endpoint: ""
  # -- MinIO endpoint port
  endpoint_port: "9000"
  # -- MinIO Access Key ID
  accessKeyId: "minio"
  # -- MinIO Secret Access Key
  accessKey: "minio123"
  # -- k8s Secret name for storage accessKeyId
  secretNameAccessKeyId: ""
  # -- Key for storage accessKeyId taken from k8s secret
  secretKeyAccessKeyId: ""
  # -- K8s Secret Name for storage secretAccessKeyId
  secretNameSecretAccessKey: ""
  # -- Key for storage secretAccessKeyId taken from k8s secret
  secretKeySecretAccessKey: ""
  # -- MinIO Region
  region: ""
  # -- MinIO Token
  token: ""
  # -- MinIO Bucket
  bucket: "testkube-artifacts"
  # -- MinIO Expiration period in days
  expiration: 0
  # -- MinIO Use SSL
  SSL: false
  # -- Toggle whether to verify TLS certificates
  skipVerify: false
  # -- If enabled, will also require a CA certificate to be provided
  mountCACertificate: false
  certSecret:
    # -- Toggle whether to mount k8s secret which contains storage client certificate (cert.crt, cert.key, ca.crt)
    enabled: false
    # -- Name of the storage client certificate secret
    name: "storage-client-cert"
    # -- Base path to mount the client certificate secret
    baseMountPath: /etc/client-certs/storage
    # -- Path to client certificate file
    certFile: "cert.crt"
    # -- Path to client certificate key file
    keyFile: "cert.key"
    # -- Path to ca file (used for self-signed certificates)
    caFile: "ca.crt"
  # -- Toggle whether to enable scraper in Testkube API
  scrapperEnabled: true
  # -- Toggle whether to compress artifacts in Testkube API
  compressArtifacts: true

## Enable a [pod distruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to help dealing with [disruptions](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/).
podDisruptionBudget:
  enabled: true
  # -- (int/percentage) Number or percentage of pods that must remain available.
  minAvailable: ""
  # -- (int/percentage) Number or percentage of pods that can be unavailable.
  maxUnavailable: ""
