apiVersion: v1
kind: Service
metadata:
  name: {{ include "testkube-api.fullname" . }}
  labels:
    {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.service.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.annotations }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
    protocol: TCP
    name: grpc
  selector: {{- include "testkube-api.selectorLabels" . | nindent 4 }}
