{{- if .Values.global.testWorkflows.createServiceAccountTemplates }}
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: serviceaccount--fullaccess
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "19"
    helm.sh/hook-delete-policy: hook-failed,before-hook-creation
spec:
  pod:
    serviceAccountName: {{ include "testkube-api.serviceAccountName" . }}
{{- end }}
