/*
 * Kubtest API
 *
 * Kubtest provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: kubtest@kubshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package kubtest

import (
	"time"
)

// execution result returned from executor
type Execution struct {
	// execution id
	Id string `json:"id,omitempty"`
	// script metadata content
	ScriptContent string      `json:"script-content,omitempty"`
	Repository    *Repository `json:"repository,omitempty"`
	// execution params passed to executor
	Params map[string]string `json:"params,omitempty"`
	Status *ExecutionStatus  `json:"status,omitempty"`
	Result *ExecutionResult  `json:"result,omitempty"`
	// test start time
	StartTime time.Time `json:"start-time,omitempty"`
	// test end time
	EndTime time.Time `json:"end-time,omitempty"`
}
