package tests

import (
	"fmt"
	"time"

	"github.com/kubeshop/testkube/pkg/ui"
	"github.com/spf13/cobra"
)

const WatchInterval = 2 * time.Second

func NewStartTestCmd() *cobra.Command {
	var (
		name                     string
		watchEnabled             bool
		params                   map[string]string
		downloadArtifactsEnabled bool
		downloadDir              string
	)

	cmd := &cobra.Command{
		Use:     "start",
		Aliases: []string{"run", "r"},
		Short:   "Starts new test",
		Long:    `Starts new test based on Test Custom Resource name, returns results to console`,
		Run: func(cmd *cobra.Command, args []string) {
			ui.Logo()

			if len(args) == 0 {
				ui.ExitOnError("Invalid arguments", fmt.Errorf("please pass test name to run"))
			}

			testID := args[0]
			startTime := time.Now()

			client, namespace := GetClient(cmd)
			namespacedName := fmt.Sprintf("%s/%s", namespace, testID)

			execution, err := client.ExecuteTest(testID, namespace, name, params)
			ui.ExitOnError("starting test execution "+namespacedName, err)

			if watchEnabled {
				executionCh, err := client.WatchTestExecution(execution.Id)
				for execution := range executionCh {
					ui.ExitOnError("watching test execution", err)
					printTestExecutionDetails(execution, startTime)
				}
			}

			execution, err = client.GetTestExecution(execution.Id)
			printTestExecutionDetails(execution, startTime)
			ui.ExitOnError("getting recent execution data id:"+execution.Id, err)

			uiPrintTestStatus(execution)

			uiShellTestGetCommandBlock(execution.Id)
			if !watchEnabled {
				uiShellTestWatchCommandBlock(execution.Id)
			}
		},
	}

	cmd.Flags().StringVarP(&name, "name", "n", "", "execution name, if empty will be autogenerated")
	cmd.Flags().StringToStringVarP(&params, "param", "p", map[string]string{}, "execution envs passed to executor")
	cmd.Flags().BoolVarP(&watchEnabled, "watch", "f", false, "watch for changes after start")
	cmd.Flags().StringVar(&downloadDir, "download-dir", "artifacts", "download dir")
	cmd.Flags().BoolVarP(&downloadArtifactsEnabled, "download-artifacts", "a", false, "downlaod artifacts automatically")

	return cmd
}
