{{- if .Values.global.testWorkflows.createOfficialTemplates }}
kind: TestWorkflowTemplate
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: official--postman--v1
  labels:
    testkube.io/name: Postman
    testkube.io/wizard: enabled
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "19"
    helm.sh/hook-delete-policy: hook-failed,before-hook-creation
    testkube.io/categories: API
    testkube.io/description: Run Postman tests
    testkube.io/icon: postman
    testkube.io/image: postman/newman
spec:
  config:
    version:
      description: Postman version to use
      type: string
      default: 6-alpine
    run:
      description: Run command
      type: string
      default: "newman run"
  steps:
  - name: Run Postman tests
    run:
      image: {{`"postman/newman:{{ config.version }}"`}}
      shell: {{`"{{ config.run }}"`}}
{{- end }}
