// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube/pkg/testworkflows/testworkflowexecutor (interfaces: TestWorkflowExecutor)

// Package testworkflowexecutor is a generated GoMock package.
package testworkflowexecutor

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/kubeshop/testkube-operator/api/testworkflows/v1"
	testkube "github.com/kubeshop/testkube/pkg/api/v1/testkube"
)

// MockTestWorkflowExecutor is a mock of TestWorkflowExecutor interface.
type MockTestWorkflowExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockTestWorkflowExecutorMockRecorder
}

// MockTestWorkflowExecutorMockRecorder is the mock recorder for MockTestWorkflowExecutor.
type MockTestWorkflowExecutorMockRecorder struct {
	mock *MockTestWorkflowExecutor
}

// NewMockTestWorkflowExecutor creates a new mock instance.
func NewMockTestWorkflowExecutor(ctrl *gomock.Controller) *MockTestWorkflowExecutor {
	mock := &MockTestWorkflowExecutor{ctrl: ctrl}
	mock.recorder = &MockTestWorkflowExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestWorkflowExecutor) EXPECT() *MockTestWorkflowExecutorMockRecorder {
	return m.recorder
}

// LegacyExecute mocks base method.
func (m *MockTestWorkflowExecutor) LegacyExecute(arg0 context.Context, arg1 v1.TestWorkflow, arg2 testkube.TestWorkflowExecutionRequest) (testkube.TestWorkflowExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LegacyExecute", arg0, arg1, arg2)
	ret0, _ := ret[0].(testkube.TestWorkflowExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LegacyExecute indicates an expected call of LegacyExecute.
func (mr *MockTestWorkflowExecutorMockRecorder) LegacyExecute(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LegacyExecute", reflect.TypeOf((*MockTestWorkflowExecutor)(nil).LegacyExecute), arg0, arg1, arg2)
}
