// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubeshop/testkube/pkg/testworkflows/testworkflowexecutor (interfaces: TestWorkflowExecutor)
//
// Generated by this command:
//
//	mockgen -destination=./mock_executor.go -package=testworkflowexecutor github.com/kubeshop/testkube/pkg/testworkflows/testworkflowexecutor TestWorkflowExecutor
//

// Package testworkflowexecutor is a generated GoMock package.
package testworkflowexecutor

import (
	context "context"
	reflect "reflect"

	testkube "github.com/kubeshop/testkube/pkg/api/v1/testkube"
	cloud "github.com/kubeshop/testkube/pkg/cloud"
	gomock "go.uber.org/mock/gomock"
)

// MockTestWorkflowExecutor is a mock of TestWorkflowExecutor interface.
type MockTestWorkflowExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockTestWorkflowExecutorMockRecorder
	isgomock struct{}
}

// MockTestWorkflowExecutorMockRecorder is the mock recorder for MockTestWorkflowExecutor.
type MockTestWorkflowExecutorMockRecorder struct {
	mock *MockTestWorkflowExecutor
}

// NewMockTestWorkflowExecutor creates a new mock instance.
func NewMockTestWorkflowExecutor(ctrl *gomock.Controller) *MockTestWorkflowExecutor {
	mock := &MockTestWorkflowExecutor{ctrl: ctrl}
	mock.recorder = &MockTestWorkflowExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestWorkflowExecutor) EXPECT() *MockTestWorkflowExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTestWorkflowExecutor) Execute(ctx context.Context, environmentId string, req *cloud.ScheduleRequest) TestWorkflowExecutionStream {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, environmentId, req)
	ret0, _ := ret[0].(TestWorkflowExecutionStream)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTestWorkflowExecutorMockRecorder) Execute(ctx, environmentId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTestWorkflowExecutor)(nil).Execute), ctx, environmentId, req)
}

// Start mocks base method.
func (m *MockTestWorkflowExecutor) Start(environmentId string, execution *testkube.TestWorkflowExecution, secrets map[string]map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", environmentId, execution, secrets)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTestWorkflowExecutorMockRecorder) Start(environmentId, execution, secrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTestWorkflowExecutor)(nil).Start), environmentId, execution, secrets)
}
