builds:
  - id: "linux"
    main: "./contrib/executor/{{ .Env.EXECUTOR }}/cmd/agent"
    binary: "{{ .Env.EXECUTOR }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}:{{ .ShortCommit }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--build-arg=TOKEN={{ .Env.GITHUB_TOKEN }}"

release:
  disable: true

snapshot:
  name_template: '{{ .ShortCommit }}'

