{{- if .Values.enabled }}
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 47f0dfc1.testkube.io
kind: ConfigMap
metadata:
  name: testkube-operator-manager-config
  namespace: {{ include "testkube-operator.namespace" . }}
{{- end }}
