apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: artifacts-junit-example
  labels:
    artifacts: "true"
    junit: "true"
    category: testing
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube
      revision: main
      paths:
      - test/playwright/playwright-project
  container:
    image: mcr.microsoft.com/playwright:v1.56.1
    resources:
      requests:
        cpu: 1500m
        memory: 1500Mi
    workingDir: /data/repo/test/playwright/playwright-project
  job:
    activeDeadlineSeconds: 600
  steps:
  - name: Install dependencies
    shell: "npm ci"
  
  - name: Run tests and generate reports
    run:
      shell: "mkdir /data/artifacts && npx playwright test --reporter=list,junit,html"
      env:
      - name: PLAYWRIGHT_JUNIT_OUTPUT_NAME
        value: "/data/artifacts/junit-report.xml"
      - name: PLAYWRIGHT_HTML_REPORT
        value: /data/artifacts/playwright-report
    steps:
    - name: Save artifacts
      condition: always  # Save artifacts even if tests fail
      artifacts:
        workingDir: /data/artifacts/
        paths:
        - '**/*'  # Capture all artifacts including junit-report.xml and playwright-report
