apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: retry-and-conditions-example
  labels:
    category: special-cases
spec:
  container:
    image: alpine:3.22.0
  job:
    activeDeadlineSeconds: 30
  steps:
  - name: Random pass/fail with retry
    retry:
      count: 20
      until: self.passed
    shell: |
      code=$((RANDOM % 2))
      [[ $code -eq 0 ]] && echo "random - passed" || echo "random - failed"
      exit $code
  
  - name: Step that might fail
    shell: |
      # Simulate a step that might fail
      exit 1
  
  - name: Always run cleanup
    condition: always
    shell: |
      echo "This step runs even if previous steps failed"
      echo "Useful for cleanup operations"
  
  - name: Run only on success
    condition: success
    shell: |
      echo "This step only runs if all previous steps succeeded"
  
  - name: Run only on failure
    condition: failure
    shell: |
      echo "This step only runs if any previous step failed"
