apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: env-override-example
  labels:
    category: special-cases
spec:
  container:
    image: alpine:3.22.0
    env:
      - name: EXAMPLE_ENV
        value: "global"
        global: true
  services:
    echo-service:
      image: alpine:3.22.0
      env:
        - name: EXAMPLE_ENV
          value: "service-env"
      shell: |
        echo "Service Literal: $EXAMPLE_ENV"
        echo "Service Expression: {{ env.EXAMPLE_ENV }}"
        [ "$EXAMPLE_ENV" = "service-env" ] && [ "{{ env.EXAMPLE_ENV }}" = "service-env" ] && echo SERVICE OK
  steps:
    - name: Check global ENV
      run:
        shell: |
          echo "Step Literal: $EXAMPLE_ENV"
          echo "Step Expression: {{ env.EXAMPLE_ENV }}"
          [ "$EXAMPLE_ENV" = "global" ] && [ "{{ env.EXAMPLE_ENV }}" = "global" ] && echo OK
    - name: Check overridden ENV
      run:
        env:
          - name: EXAMPLE_ENV
            value: "step-local"
        shell: |
          echo "Step Literal: $EXAMPLE_ENV"
          echo "Step Expression: {{ env.EXAMPLE_ENV }}"
          [ "$EXAMPLE_ENV" = "step-local" ] && [ "{{ env.EXAMPLE_ENV }}" = "step-local" ] && echo OK
    - name: Parallel ENV checks
      parallel:
        steps:
          - name: Check global (parallel)
            run:
              shell: |
                echo "Parallel Literal: $EXAMPLE_ENV"
                echo "Parallel Expression: {{ env.EXAMPLE_ENV }}"
                [ "$EXAMPLE_ENV" = "global" ] && [ "{{ env.EXAMPLE_ENV }}" = "global" ] && echo OK
          - name: Check overridden (parallel)
            run:
              env:
                - name: EXAMPLE_ENV
                  value: "parallel-override"
              shell: |
                echo "Parallel Literal: $EXAMPLE_ENV"
                echo "Parallel Expression: {{ env.EXAMPLE_ENV }}"
                [ "$EXAMPLE_ENV" = "parallel-override" ] && [ "{{ env.EXAMPLE_ENV }}" = "parallel-override" ] && echo OK
