/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// configuration to control concurrent executions.
type TestWorkflowConcurrencyPolicy struct {
	// Group ongoing executions by this identifier instead of by workflow name. Use the group identifier if you want the control concurrency across workflows.
	Group string `json:"group,omitempty"`
	// The maximum amount of concurrent executions for this workflow or group. The scheduler will check the amount of ongoing executions for this workflow or group and only schedule this workflow when the amount is below its given maximum. When using a group identifier, it is recommended to keep the maximum in sync through a WorkflowTemplate.
	Max int32 `json:"max,omitempty"`
	// Whether the oldest in progress execution should be cancelled to be replaced with the latest queued one.
	CancelInProgress bool `json:"cancelInProgress,omitempty"`
}
