/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// supported action parameters for test triggers
type TestTriggerActionParameters struct {
	Config map[string]string `json:"config,omitempty"`
	Tags   map[string]string `json:"tags,omitempty"`
	Target *ExecutionTarget  `json:"target,omitempty"`
}
