/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// Secret input information to update
type SecretUpdate struct {
	// secret name
	Name  *string      `json:"name,omitempty"`
	Owner *SecretOwner `json:"owner,omitempty"`
	// labels associated with the secret
	Labels *map[string]string `json:"labels,omitempty"`
	// data to store in the secret
	Data *map[string]string `json:"data,omitempty"`
}
