/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type TestTriggerSelector struct {
	// kubernetes resource name selector
	Name string `json:"name,omitempty"`
	// kubernetes resource name regex
	NameRegex string `json:"nameRegex,omitempty"`
	// resource namespace
	Namespace string `json:"namespace,omitempty"`
	// kubernetes resource namespace regex
	NamespaceRegex string                                       `json:"namespaceRegex,omitempty"`
	LabelSelector  *IoK8sApimachineryPkgApisMetaV1LabelSelector `json:"labelSelector,omitempty"`
}
