/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// test workflow execution configuration
type TestWorkflowExecutionSchema struct {
	Tags   map[string]string `json:"tags,omitempty"`
	Target *ExecutionTarget  `json:"target,omitempty"`
	// indicates that all executions should be silent by default. When true, SilentMode is activated for all executions (Webhooks, Insights, Health, Metrics, Cdevents all set to true).
	Silent bool `json:"silent,omitempty"`
}
