/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type ExecutionTargetMatch struct {
	// accepted values to match
	OneOf []string `json:"oneOf,omitempty"`
	// not accepted values to match
	NotOneOf []string `json:"notOneOf,omitempty"`
}
