/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// the person who canceled the execution; the control plane fills it
type TestWorkflowStatusDetailsUser struct {
	Name  string `json:"name,omitempty"`
	Email string `json:"email,omitempty"`
}
