/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// TestWorkflowRunningContextActor : supported actors for test workflow running context
type TestWorkflowRunningContextActor string

// List of TestWorkflowRunningContextActor
const (
	CRON_TestWorkflowRunningContextActor       TestWorkflowRunningContextActor = "cron"
	TESTRIGGER_TestWorkflowRunningContextActor TestWorkflowRunningContextActor = "testrigger"
	USER_TestWorkflowRunningContextActor       TestWorkflowRunningContextActor = "user"
)
