/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// TestWorkflowExecutionResourceAggregationsScope : Scope of the resource metrics aggregations.
type TestWorkflowExecutionResourceAggregationsScope string

// List of TestWorkflowExecutionResourceAggregationsScope
const (
	STEP_TestWorkflowExecutionResourceAggregationsScope   TestWorkflowExecutionResourceAggregationsScope = "step"
	GLOBAL_TestWorkflowExecutionResourceAggregationsScope TestWorkflowExecutionResourceAggregationsScope = "global"
)
