/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type Variable struct {
	Name         string        `json:"name,omitempty"`
	Value        string        `json:"value,omitempty"`
	Type_        *VariableType `json:"type,omitempty"`
	SecretRef    *SecretRef    `json:"secretRef,omitempty"`
	ConfigMapRef *ConfigMapRef `json:"configMapRef,omitempty"`
}
