/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type TestWorkflowReport struct {
	// step reference
	Ref string `json:"ref,omitempty"`
	// report kind/type
	Kind string `json:"kind,omitempty"`
	// file path to full report in artifact storage
	File    string                     `json:"file,omitempty"`
	Summary *TestWorkflowReportSummary `json:"summary,omitempty"`
}
