/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// what this step's test report means: which failing test cases may be tolerated, what the pass requirement is, and which test cases this run should be narrowed to.  Available in connected mode only.
type TestWorkflowStepTestCases struct {
	Report   *TestWorkflowTestCaseReport    `json:"report,omitempty"`
	Mute     *TestWorkflowTestCaseSelector  `json:"mute,omitempty"`
	Tolerate *TestWorkflowTestCaseTolerance `json:"tolerate,omitempty"`
	// how far the policy may move the verdict: onFailure (default) only turns a failure into a pass, always additionally fails a zero-exit run that misses the requirement.
	Enforce string                         `json:"enforce,omitempty"`
	Select_ *TestWorkflowTestCaseSelection `json:"select,omitempty"`
}
