/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

import (
	"time"
)

// Test suite batch executions data
type TestSuiteBatchExecution struct {
	// execution id
	Id string `json:"id"`
	// execution name
	Name      string                    `json:"name"`
	TestSuite *ObjectRef                `json:"testSuite"`
	Status    *TestSuiteExecutionStatus `json:"status,omitempty"`
	// environment variables passed to executor
	Envs      map[string]string   `json:"envs,omitempty"`
	Variables map[string]Variable `json:"variables,omitempty"`
	// secret uuid
	SecretUUID string `json:"secretUUID,omitempty"`
	// test start time
	StartTime time.Time `json:"startTime,omitempty"`
	// test end time
	EndTime time.Time `json:"endTime,omitempty"`
	// test duration
	Duration string `json:"duration,omitempty"`
	// test duration in ms
	DurationMs int32 `json:"durationMs,omitempty"`
	// batch steps execution results
	BatchStepResults []TestSuiteBatchStepExecutionResult `json:"batchStepResults,omitempty"`
	// test suite labels
	Labels map[string]string `json:"labels,omitempty"`
}
