/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type TestWorkflowParameterSchema struct {
	// human-readable description for the property
	Description string                     `json:"description,omitempty"`
	Type_       *TestWorkflowParameterType `json:"type"`
	// list of acceptable values
	Enum []string `json:"enum,omitempty"`
	// example value for the parameter
	Example  string       `json:"example,omitempty"`
	Default_ *BoxedString `json:"default,omitempty"`
	// predefined format for the string
	Format string `json:"format,omitempty"`
	// regular expression to match
	Pattern          string        `json:"pattern,omitempty"`
	MinLength        *BoxedInteger `json:"minLength,omitempty"`
	MaxLength        *BoxedInteger `json:"maxLength,omitempty"`
	Minimum          *BoxedInteger `json:"minimum,omitempty"`
	Maximum          *BoxedInteger `json:"maximum,omitempty"`
	ExclusiveMinimum *BoxedInteger `json:"exclusiveMinimum,omitempty"`
	ExclusiveMaximum *BoxedInteger `json:"exclusiveMaximum,omitempty"`
	MultipleOf       *BoxedInteger `json:"multipleOf,omitempty"`
}
