/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// running context caller for test workflow execution
type TestWorkflowRunningContextCaller struct {
	CallerResourceType *TestWorkflowRunningContextCallerResourceType `json:"callerResourceType"`
	// caller resource name
	CallerResourceName string `json:"callerResourceName"`
	// caller resource execution id
	CallerResourceExecutionID string `json:"callerResourceExecutionID"`
	// all test workflow execution ids starting from the root
	FullExecutionPath string `json:"fullExecutionPath"`
}
