/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// test content update body
type TestContentUpdate struct {
	// test type
	Type_      *string            `json:"type,omitempty"`
	Repository **RepositoryUpdate `json:"repository,omitempty"`
	// test content data as *string
	Data *string `json:"data,omitempty"`
	// test content
	Uri *string `json:"uri,omitempty"`
}
