/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: contact@testkube.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// ClusterTrustBundle allows a pod to access the `.spec.trustBundle` field of ClusterTrustBundle objects in an auto-updating file.
type ProjectedVolumeSourceClusterTrustBundle struct {
	LabelSelector *LabelSelector `json:"labelSelector,omitempty"`
	Name          *BoxedString   `json:"name,omitempty"`
	Optional      *BoxedBoolean  `json:"optional,omitempty"`
	// Relative path from the volume root to write the bundle.
	Path       string       `json:"path"`
	SignerName *BoxedString `json:"signerName,omitempty"`
}
