/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type Variables *[]Variable

func NewBasicVariable(name, value string) Variable {
	return Variable{
		Name:  name,
		Value: value,
		Type_: VariableTypeBasic,
	}
}

func NewSecretVariable(name, value string) Variable {
	return Variable{
		Name:  name,
		Value: value,
		Type_: VariableTypeSecret,
	}
}

func NewVariablesFromMap(paramsCollection ...map[string]string) *[]Variable {
	vars := []Variable{}

	// flatten first, override duplicates
	params := map[string]string{}
	for _, p := range paramsCollection {
		for k, v := range p {
			params[k] = v
		}
	}

	for k, v := range params {
		vars = append(vars, NewBasicVariable(k, v))

	}

	return &vars
}
