/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type TestWorkflowContentFile struct {
	// path where the file should be accessible at
	Path string `json:"path"`
	// plain-text content to put inside
	Content     string        `json:"content,omitempty"`
	ContentFrom *EnvVarSource `json:"contentFrom,omitempty"`
	Mode        *BoxedInteger `json:"mode,omitempty"`
}
