/*
 * TestKube API
 *
 * TestKube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type TestStepType string

// List of TestStepType
const (
	EXECUTE_SCRIPT_TestStepType TestStepType = "executeScript"
	DELAY_TestStepType          TestStepType = "delay"
)
