/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

type SecretOwnerKind string

// List of SecretOwnerKind
const (
	TEST_WORKFLOW_SecretOwnerKind          SecretOwnerKind = "TestWorkflow"
	TEST_WORKFLOW_TEMPLATE_SecretOwnerKind SecretOwnerKind = "TestWorkflowTemplate"
)
