/*
 * Testkube API
 *
 * Testkube provides a Kubernetes-native framework for test definition, execution and results
 *
 * API version: 1.0.0
 * Contact: testkube@kubeshop.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testkube

// test suite step update body
type TestSuiteStepUpdate struct {
	StopTestOnFailure *bool                            `json:"stopTestOnFailure"`
	Execute           **TestSuiteStepExecuteTestUpdate `json:"execute,omitempty"`
	Delay             **TestSuiteStepDelayUpdate       `json:"delay,omitempty"`
}
