name: Docker images building and pushing
on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Docker meta for executor
        id: meta_executor
        uses: docker/metadata-action@v3
        with:
        #Specify image name, e.g. kubeshop/testkube-executor-init
          images: image_name
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - 
        name: Build Executor Init
        uses: docker/bake-action@v1
        with:
          files: |
            build/agent/docker-bake.hcl
            ${{ steps.meta_executor.outputs.bake-file }}
          targets: build
          push: true


