name: "Linting"

on:
  push:
    branches-ignore:
      - main
      - renovate/**
      - dependabot/**

permissions:
  # allow read access to the content for analysis.
  contents: read
  # allow read access to pull requests. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: depot-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'

      - name: Lint Go
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout=10m
          only-new-issues: true
          verify: true

      - name: Lint Protocol Buffers
        uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
        with:
          version: 1.68.1
          # Prevent buf from attempting to create a PR comment.
          pr_comment: false
          # buf config files are in the ./proto directory.
          input: proto
          # This is required to avoid the breaking change check
          # from failing due to the imports from the legacy
          # proto definitions, it should still allow for valid
          # breaking change detection of our own new protos.
          exclude_imports: true
          # Ignore the legacy protos from formatting, they are
          # also excluded in the buf.yaml file for breaking and
          # linting checks.
          exclude_paths: |
            proto/logs.proto
            proto/service.proto

#      - name: Lint OpenAPI
#        uses: swaggerexpert/swagger-editor-validate@v1
#        with:
#          definition-file: api/v1/testkube.yaml
#          default-timeout: 20000
